### ISSUE TITLE
https://apisnoop.cncf.io ingress not working

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#149]
# Request: Ensure https for apisnoop.cncf.{ci,io}

## Short description:

- Current state:
  -  http://apisnoop.cncf.io => 404
  -  https://apisnoop.cncf.io shows kubernetes ingress and self signed cert and 404

ingress not working
- Desired state:
  - http://apisnoop.cncf.io 301 redirects to https://apisnoop.cncf.io
  - https://apisnoop.cncf.io connects to production deployment

### Tasks:
- [x] configure 301 redirect ingress 
- [x] configure ssl ingress

**Comment by devaii** [comment]
New ingress has been applied:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://apisnoop.cncf.ci"
  name: cncf-io-to-production
spec:
  tls:
  - secretName: apisnoop-cncf-io-tls
    hosts:
    - apisnoop.cncf.io
  rules:
    - host: apisnoop.cncf.io
      http:
        paths:
          - backend:
              serviceName: production-auto-deploy
              servicePort: 5000
            path: /
```

The nginx-ingress-controller was not picking up the new secret. This has not been an [uncommon](https://github.com/kubernetes/ingress-nginx/issues/879) [problem](https://github.com/kubernetes/ingress-nginx/issues/947). Restarting the ingress controller pod resolved the issue.

```
$ curl https://apisnoop.cncf.io

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.13.8</center>
</body>
</html>
```

Looks good.
