### ISSUE TITLE
Literately go from bare metal to kind+kubetest

### ISSUE THREAD

**Issue by hh** [cncf/apisnoop#168]
Put together an literate org (and it's md)

### Tasks:
- [ ] Provision Packet (or use local box)
- [ ] X

**Comment by heyste** [comment]
**Tasks:**

- [ ] Provision hardware 
  - Use Packet or local box
- [ ] Install dependencies
  - docker
  - git & gcc
  - go
  - kubectl
- [ ] Download core software 
  - kubernetes
  - kubetest
  - kind
- [ ] Provision kubernetes cluster
  - Build kubetest
  - Provision cluster via kubetest
- [ ] Health checks
  - docker
  - kubernetes

**Comment by hh** [comment]
@hestye we will need the kubetest parameters to run kind based tests and also extract the audit-logs:

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/kind/kind.yaml#L130

```
# conformance test against kubernetes master branch with `kind`, skipping
# serial tests so it runs in ~20m
- interval: 20m
  name: ci-kubernetes-kind-conformance-parallel
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20190329-811f7954b-master
      env:
      # skip serial tests and run with --ginkgo-parallel
      - name: "PARALLEL"
        value: "true"
      args:
      - "--job=$(JOB_NAME)"
      - "--root=/go/src"
      - "--repo=k8s.io/kubernetes=master"
      - "--repo=sigs.k8s.io/kind=master"
      - "--service-account=/etc/service-account/service-account.json"
      - "--upload=gs://kubernetes-jenkins/logs"
      - "--scenario=execute"
      - "--"
      - "./../../sigs.k8s.io/kind/hack/ci/e2e.sh"
      # we need privileged mode in order to do docker in docker
      securityContext:
        privileged: true
      resources:
        requests:
          # these are both a bit below peak usage during build
          # this is mostly for building kubernetes
          memory: "9000Mi"
          # during the tests more like 3-20m is used
          cpu: 2000m

```
